name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64

      - name: Build Project
        run: |
          New-Item -ItemType directory -Path build
          cmake -S . -B build
          cmake --build build/ --config Debug -j

      - name: Upload build files
        uses: actions/upload-artifact@v3.1.3
        with:
          name: artifact
          path: |
            ./build/Debug
